name: PlatformIO Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build firmware
        run: |
          docker run -v ${{ github.workspace }}:/project -w /project platformio/platformio:latest run

      - name: Upload firmware
        run: |
          docker run -v ${{ github.workspace }}:/project -w /project platformio/platformio:latest run --target upload

  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker run -v ${{ github.workspace }}:/project -w /project platformio/platformio:latest test
